services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks: 
      - observability
  nginx:
    build: ./nginx
    ports:
      - "8000:80"
    networks:
      - observability
networks:
  observability:
    external: true    
